# .travis.yml
language: python
env:
  - LUA="lua=5.1.5"
before_install:
  - sudo ./install-dev.sh

install:
  - pip install openwisp-utils[qa]>=0.3.1

script:
  - openwisp-utils-qa-checks --skip-checkmigrations --skip-isort --skip-flake8
  - ./runtests
